In [20]:
import pandas as pd

df = pd.read_csv("loja.csv", sep=";", decimal=",")
df

,ID Faturamento,Filial,Bairro,Tipo Cliente,Genero,Tipo de produto,Preco unidade,Quantidade,Taxa 5%,Total,Data,Hora,Pagamento,cogs,porcentagem de margem bruta,renda bruta,Nota
0,750-67-8428,A,Benfica,Membro,Feminino,Saúde e Beleza,74.69,7,26.1415,548.9715,10/5/2024,13:08,Pix,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Aldeota,Normal,Feminino,Eletrônicos,15.28,5,3.8200,80.2200,12/8/2024,10:29,Dinheiro,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Benfica,Normal,Masculino,Itens do Lar,46.33,7,16.2155,340.5255,12/12/2024,13:23,Cartão de Crédito,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Benfica,Membro,Masculino,Saúde e Beleza,58.22,8,23.2880,489.0480,10/27/2024,20:33,Pix,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Benfica,Normal,Masculino,Esportes e Lazer,86.31,7,30.2085,634.3785,11/8/2024,10:37,Pix,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Aldeota,Normal,Masculino,Saúde e Beleza,40.35,1,2.0175,42.3675,10/29/2024,13:46,Pix,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Parangaba,Normal,Feminino,Itens do Lar,97.38,10,48.6900,1022.4900,12/11/2024,17:16,Pix,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Benfica,Membro,Masculino,Alimentícios,31.84,1,1.5920,33.4320,11/9/2024,13:22,Dinheiro,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Benfica,Normal,Masculino,Itens do Lar,65.82,1,3.2910,69.1110,11/21/2024,15:33,Dinheiro,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Benfica,Membro,Feminino,Vestuário,88.34,7,30.9190,649.2990,11/18/2024,13:28,Dinheiro,618.38,4.761905,30.9190,6.6

In [21]:
# ajustando a data
df["Data"] = pd.to_datetime(df["Data"])
df = df.sort_values("Data")
df

,ID Faturamento,Filial,Bairro,Tipo Cliente,Genero,Tipo de produto,Preco unidade,Quantidade,Taxa 5%,Total,Data,Hora,Pagamento,cogs,porcentagem de margem bruta,renda bruta,Nota
156,279-74-2924,B,Parangaba,Membro,Masculino,Eletrônicos,72.17,1,3.6085,75.7785,2024-10-04,19:40,Dinheiro,72.17,4.761905,3.6085,6.1
206,672-51-8681,C,Aldeota,Membro,Feminino,Eletrônicos,66.65,9,29.9925,629.8425,2024-10-04,18:19,Cartão de Crédito,599.85,4.761905,29.9925,9.7
213,656-16-1063,B,Parangaba,Normal,Masculino,Esportes e Lazer,46.42,3,6.9630,146.2230,2024-10-04,13:24,Cartão de Crédito,139.26,4.761905,6.9630,4.4
269,731-14-2199,A,Benfica,Membro,Feminino,Itens do Lar,35.54,10,17.7700,373.1700,2024-10-04,13:34,Pix,355.40,4.761905,17.7700,7.0
407,725-32-9708,B,Parangaba,Membro,Feminino,Vestuário,68.71,4,13.7420,288.5820,2024-10-04,19:01,Dinheiro,274.84,4.761905,13.7420,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,743-04-1105,B,Parangaba,Membro,Masculino,Saúde e Beleza,97.22,9,43.7490,918.7290,2024-12-30,14:43,Pix,874.98,4.761905,43.7490,6.0
671,642-61-4706,B,Parangaba,Membro,Masculino,Alimentícios,93.40,2,9.3400,196.1400,2024-12-30,16:34,Dinheiro,186.80,4.761905,9.3400,5.5
306,286-01-5402,A,Benfica,Normal,Feminino,Esportes e Lazer,40.23,7,14.0805,295.6905,2024-12-30,13:22,Dinheiro,281.61,4.761905,14.0805,9.6
937,361-85-2571,A,Benfica,Normal,Feminino,Esportes e Lazer,89.48,5,22.3700,469.7700,2024-12-30,10:18,Dinheiro,447.40,4.761905,22.3700,7.4
643,131-15-8856,C,Aldeota,Membro,Feminino,Alimentícios,72.52,8,29.0080,609.1680,2024-12-30,19:26,Cartão de Crédito,580.16,4.761905,29.0080,4.0

In [22]:
# criando coluna para o mês
meses = df["Data"].apply(lambda x: str(x.year) + "-" + str(x.month))

# inserindo a coluna meses no dataframe, ao lado da data completa
df.insert(11, "Mes", meses)
df

,ID Faturamento,Filial,Bairro,Tipo Cliente,Genero,Tipo de produto,Preco unidade,Quantidade,Taxa 5%,Total,Data,Mes,Hora,Pagamento,cogs,porcentagem de margem bruta,renda bruta,Nota
156,279-74-2924,B,Parangaba,Membro,Masculino,Eletrônicos,72.17,1,3.6085,75.7785,2024-10-04,2024-10,19:40,Dinheiro,72.17,4.761905,3.6085,6.1
206,672-51-8681,C,Aldeota,Membro,Feminino,Eletrônicos,66.65,9,29.9925,629.8425,2024-10-04,2024-10,18:19,Cartão de Crédito,599.85,4.761905,29.9925,9.7
213,656-16-1063,B,Parangaba,Normal,Masculino,Esportes e Lazer,46.42,3,6.9630,146.2230,2024-10-04,2024-10,13:24,Cartão de Crédito,139.26,4.761905,6.9630,4.4
269,731-14-2199,A,Benfica,Membro,Feminino,Itens do Lar,35.54,10,17.7700,373.1700,2024-10-04,2024-10,13:34,Pix,355.40,4.761905,17.7700,7.0
407,725-32-9708,B,Parangaba,Membro,Feminino,Vestuário,68.71,4,13.7420,288.5820,2024-10-04,2024-10,19:01,Dinheiro,274.84,4.761905,13.7420,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,743-04-1105,B,Parangaba,Membro,Masculino,Saúde e Beleza,97.22,9,43.7490,918.7290,2024-12-30,2024-12,14:43,Pix,874.98,4.761905,43.7490,6.0
671,642-61-4706,B,Parangaba,Membro,Masculino,Alimentícios,93.40,2,9.3400,196.1400,2024-12-30,2024-12,16:34,Dinheiro,186.80,4.761905,9.3400,5.5
306,286-01-5402,A,Benfica,Normal,Feminino,Esportes e Lazer,40.23,7,14.0805,295.6905,2024-12-30,2024-12,13:22,Dinheiro,281.61,4.761905,14.0805,9.6
937,361-85-2571,A,Benfica,Normal,Feminino,Esportes e Lazer,89.48,5,22.3700,469.7700,2024-12-30,2024-12,10:18,Dinheiro,447.40,4.761905,22.3700,7.4
643,131-15-8856,C,Aldeota,Membro,Feminino,Alimentícios,72.52,8,29.0080,609.1680,2024-12-30,2024-12,19:26,Cartão de Crédito,580.16,4.761905,29.0080,4.0

In [28]:
# filtrando pela coluna meses no dataframe
mes = df["Mes"].unique()

df_filtrado = df[df["Mes"] == mes[0]]
df_filtrado

,ID Faturamento,Filial,Bairro,Tipo Cliente,Genero,Tipo de produto,Preco unidade,Quantidade,Taxa 5%,Total,Data,Mes,Hora,Pagamento,cogs,porcentagem de margem bruta,renda bruta,Nota
156,279-74-2924,B,Parangaba,Membro,Masculino,Eletrônicos,72.17,1,3.6085,75.7785,2024-10-04,2024-10,19:40,Dinheiro,72.17,4.761905,3.6085,6.1
206,672-51-8681,C,Aldeota,Membro,Feminino,Eletrônicos,66.65,9,29.9925,629.8425,2024-10-04,2024-10,18:19,Cartão de Crédito,599.85,4.761905,29.9925,9.7
213,656-16-1063,B,Parangaba,Normal,Masculino,Esportes e Lazer,46.42,3,6.9630,146.2230,2024-10-04,2024-10,13:24,Cartão de Crédito,139.26,4.761905,6.9630,4.4
269,731-14-2199,A,Benfica,Membro,Feminino,Itens do Lar,35.54,10,17.7700,373.1700,2024-10-04,2024-10,13:34,Pix,355.40,4.761905,17.7700,7.0
407,725-32-9708,B,Parangaba,Membro,Feminino,Vestuário,68.71,4,13.7420,288.5820,2024-10-04,2024-10,19:01,Dinheiro,274.84,4.761905,13.7420,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,286-75-7818,B,Parangaba,Normal,Masculino,Vestuário,69.08,2,6.9080,145.0680,2024-10-31,2024-10,19:48,Cartão de Crédito,138.16,4.761905,6.9080,6.9
310,532-59-7201,B,Parangaba,Membro,Masculino,Esportes e Lazer,79.93,6,23.9790,503.5590,2024-10-31,2024-10,14:04,Dinheiro,479.58,4.761905,23.9790,5.5
220,239-36-3640,B,Parangaba,Normal,Masculino,Eletrônicos,45.35,6,13.6050,285.7050,2024-10-31,2024-10,13:44,Pix,272.10,4.761905,13.6050,6.1
227,583-72-1480,C,Aldeota,Membro,Masculino,Eletrônicos,37.06,4,7.4120,155.6520,2024-10-31,2024-10,16:24,Pix,148.24,4.761905,7.4120,9.7
287,226-71-3580,C,Aldeota,Normal,Feminino,Esportes e Lazer,23.75,9,10.6875,224.4375,2024-10-31,2024-10,12:02,Dinheiro,213.75,4.761905,10.6875,9.5

In [30]:
total_bairro = df_filtrado.groupby("Bairro")[["Total"]].sum().reset_index()
total_bairro

      Bairro       Total
0    Aldeota  40434.6810
1    Benfica  38681.1285
2  Parangaba  37176.0585

In [31]:
notas = df_filtrado.groupby("Bairro")[["Nota"]].mean().reset_index()
notas

      Bairro      Nota
0    Aldeota  7.154918
1    Benfica  7.078151
2  Parangaba  6.801802

In [33]:
produtos = df_filtrado.groupby("Tipo de produto")[["Quantidade"]].sum().reset_index()
produtos

    Tipo de produto  Quantidade
0      Alimentícios         325
1       Eletrônicos         333
2  Esportes e Lazer         375
3      Itens do Lar         342
4    Saúde e Beleza         254
5         Vestuário         336